# -*- coding: utf-8 -*-
"""把 14 门新课挂进 build_site.py；旧课程(无 books 源)移出构建列表但保留预构建页面"""
import re

s = open("build_site.py", encoding="utf-8").read()

NEW = '''NEW_COURSES = [
  dict(id='presales/spb-presales', book='spb-presales', title='DT00XPS279 · OmniSwitch LAN SPB 售前',
       subtitle='Issue 05 · 147 页 · SPB 技术推销课（卖点弹药/架构/L3 服务/案例/三技术对比）',
       route=['售前攻防弹药库：为什么弃 STP 选 SPB', '架构与控制面/数据面：BEB/BCB/BVLAN/IS-IS/ECT',
              'L3 集成三形态：Outline/Front-panel/Service-based', 'OV2500 编排与三大成功案例', 'SPB vs EVPN vs MPLS 七维选型'],
       groups=[
        ('售前攻防', ['spb-presales-battlecard', 'spb-micro-segmentation']),
        ('架构与设计', ['spb-topology-isis-design']),
        ('边缘与服务', ['spb-edge-services']),
        ('L3 集成', ['spb-l3-integration']),
        ('交付与选型', ['spb-ov2500-delivery', 'spb-vs-evpn-mpls-selection', 'spb-stp-migration-cases', 'spb-license-spec-sizing']),
       ]),
  dict(id='presales/campus-lan', book='campus-lan-presales', title='DT00XPS281 · Campus LAN 售前',
       subtitle='Edition 29 · 480 页 · 园区网售前全科（特性→网管→选型→License→产品组合）',
       route=['分层设计与高可用六方案', '机型定位表→功能矩阵→VC vs 机箱', '参考架构模板库（SMB/紧凑核心/环网/密集核心）',
              '网管三平台与 Network Advisor', 'WWPL 报价规则与安全统一接入'],
       groups=[
        ('设计与高可用', ['campus-design-tiering-and-ha', 'virtual-chassis-design', 'dhl-erp-ring-protection']),
        ('机型与架构', ['omniswitch-model-selection', 'campus-reference-architectures']),
        ('织物与自动化', ['spb-vxlan-core-fabric', 'ifab-zero-touch-automation']),
        ('网管与商务', ['nms-platform-and-network-advisor', 'license-wwpl-pricing']),
        ('安全与垂直', ['security-unified-access', 'video-surveillance-design']),
       ]),
  dict(id='presales/stellar-wlan', book='stellar-wlan-presales', title='DT00XPS288 · OmniAccess Stellar WLAN 售前',
       subtitle='Edition 28 · 273 页 · 无线售前全科（AP 矩阵/三管理模式/License 三体系/用例/VoWLAN）',
       route=['AP 三维选型矩阵', '管理模式三岔口（Express/本地/云）', 'License 三体系报价法（OVCX 63 编码）',
              '七大行业用例弹药库', 'VoWLAN 与场景化容量基线'],
       groups=[
        ('选型与模式', ['ap-selection-matrix', 'management-mode-selection']),
        ('商务与报价', ['license-quotation']),
        ('用例与语音', ['industry-use-cases', 'vowlan-deployment']),
        ('场景与增值', ['rf-scenario-baseline', 'network-advisor-aiops', 'special-topologies']),
       ]),
  dict(id='postsales/acfe-wlan-basic', book='acfe-wlan', title='DT00XTE360 · ACFE WLAN Basic Deployment with OmniVista',
       subtitle='Edition 04 · 585 页 · Stellar+Cirrus 云管交付实操（AP 生命周期全流程，5 天带 Lab）',
       route=['部署模式判定与开局前置', 'Cirrus 组织与 License 生命周期', '设备 Onboarding 与激活排障',
              'SSID 全家桶与 PSK 四级体系', 'UPAM 策略/RF 基线/漫游 RAP/WIPS/勘测'],
       groups=[
        ('开局与云管', ['express-mode-bootstrap', 'cirrus-license-org-lifecycle', 'device-cloud-onboarding']),
        ('SSID 与策略', ['ssid-authentication-suite', 'upam-policy-bandwidth']),
        ('RF 与漫游', ['rf-optimization-baseline', 'roaming-rap-design']),
        ('安全与收尾', ['wips-security-deployment', 'site-survey-troubleshooting', 'rlab-lab-manual']),
       ]),
  dict(id='postsales/stellar-adv-trouble', book='stellar-wlan-adv-trouble', title='DT00XTE478 · Stellar WLAN 高级排障',
       subtitle='187 页 · 无线排障专题（方法论/工具箱/四层排障/勘测/TKC）',
       route=['排障总方法论：七步流程+三域根因地图', '排障工具箱与基础体检', '客户端连接决策链与 802.1X 排查',
              '网络侧与漫游 RF 排障', '勘测三步法与五发现五动作'],
       groups=[
        ('方法论', ['wlan-trouble-methodology']),
        ('工具与体检', ['stellar-ap-toolbox', 'stellar-ap-system-health']),
        ('故障域', ['client-connection-trouble', 'dot1x-radius-trouble', 'network-side-trouble', 'wireless-rf-roaming-trouble']),
        ('勘测纠正', ['site-survey-remediation']),
       ]),
  dict(id='postsales/stellar-express', book='stellar-wlan-express', title='DT00XTE455 · Stellar WLAN Express',
       subtitle='Edition 07 · 183 页 · 免云管小微交付专题（集群/SSID/Bridge-Mesh/15 排障案例）',
       route=['开箱六步与集群上线', 'SSID/Portal/内置服务', '射频勘测与调优',
              'Bridge/Mesh 特殊组网', '15 案例三域排障地图'],
       groups=[
        ('开局', ['express-cluster-onboarding']),
        ('业务与射频', ['ssid-portal-auth', 'rf-survey-tuning']),
        ('组网与排障', ['bridge-mesh-deployment', 'ap-side-troubleshooting']),
       ]),
  dict(id='postsales/os-lan-spb-impl', book='os-lan-spb-impl', title='DT00XTE323 · OmniSwitch LAN SPB 实施',
       subtitle='Edition 12 · 367 页 · SPB 交付配置手册（骨干→L2→L3→自动化，10 Lab CLI 全录）',
       route=['骨干部署四步（BCB/BEB/BVLAN/IS-IS）', 'L2 服务五步开通（SAP/ISID/vlan-xlation）',
              'IP over SPB 三方案配置模板', 'BUM 组播与接入保护', 'UNP 动态服务/OV2500 编排/E-Tree'],
       groups=[
        ('骨干与 L2', ['spb-backbone-deploy', 'spb-l2-service']),
        ('L3 集成', ['ip-over-spb']),
        ('保护与冗余', ['spb-bum-protection', 'spb-access-ring-redundancy', 'spb-hybrid-etree']),
        ('自动化与运维', ['unp-dynamic-ov2500', 'spb-oam-troubleshoot']),
       ]),
  dict(id='postsales/os-lan-mpls-impl', book='os-lan-mpls-impl', title='DT00XTE324 · OmniSwitch LAN MPLS 实施',
       subtitle='Edition 02 · 153 页 · MPLS/VPLS 实施精要（三 Lab CLI + 参考设计 + 能力边界）',
       route=['MPLS 部署十步与许可', 'VPLS 双信令（LDP vs BGP）选型与配置', '园区/城域参考设计模板',
              '运行规则与 show 判读', 'AOS 六项能力边界（售前禁引核对）'],
       groups=[
        ('部署与信令', ['aos-mpls-deploy-license', 'vpls-signaling-ldp-vs-bgp']),
        ('设计与运维', ['mpls-reference-design', 'aos-mpls-operating-rules', 'aos-mpls-capability-limits']),
       ]),
  dict(id='postsales/os-lan-vxlan-evpn', book='os-lan-vxlan-evpn', title='DT00XTE325 · OmniSwitch LAN VxLAN/EVPN',
       subtitle='Edition 01 · 213 页 · 五步配置法 + 三 Lab + EVPN 架构指南',
       route=['五步配置法总纲与版本边界', 'Underlay/Overlay BGP 设计', 'L2/L3 业务开通（VNI/IRB/RT 总表）',
              '多归属与 DF', 'BUM 与验证排障'],
       groups=[
        ('总纲与底座', ['vxlan-evpn-five-step-architecture', 'vxlan-evpn-underlay-bgp-design']),
        ('业务与多归属', ['vxlan-evpn-service-provisioning', 'vxlan-evpn-multihoming-df']),
        ('排障', ['vxlan-evpn-bum-troubleshooting']),
       ]),
  dict(id='postsales/os-lan-access', book='os-lan-access-switching', title='DT00XTE215 · OmniSwitch LAN Access Switching',
       subtitle='Edition 19 · 500 页 · 接入层基础全科（三目录模型/VC/VLAN/LACP/STP/DHL/QoS/AG）',
       route=['AOS 三目录配置管理模型', 'Virtual Chassis 部署运维', 'VLAN 与链路冗余（LACP/STP/DHL）',
              'IP 服务与 QoS/ACL', '接入安全（AG/UNP/LLDP）与 PoE 运维'],
       groups=[
        ('管理面', ['aos-config-management', 'switch-management-access']),
        ('转发面', ['virtual-chassis-deployment', 'vlan-link-redundancy']),
        ('策略面', ['ip-services-basic', 'qos-acl-policy', 'access-guardian-unp']),
        ('运维', ['poe-ops-diagnostics']),
       ]),
  dict(id='postsales/os-lan-troubleshooting', book='os-lan-troubleshooting', title='DT00XTE221 · OmniSwitch LAN Troubleshooting',
       subtitle='587 页 · 有线排障全科（方法论/启动/系统/L2/VC/STP/L3/组播/OVNA）',
       route=['排障总方法论与 TKC', '启动与系统排障', 'L2/STP 环路/VC 四层递进',
              'L3 路由 VRRP 与组播', '日志工具层与 OVNA AI 运维'],
       groups=[
        ('方法论与系统', ['lan-troubleshooting-methodology', 'boot-system-troubleshooting']),
        ('故障域', ['l2-connectivity-troubleshooting', 'stp-loop-troubleshooting', 'virtual-chassis-troubleshooting',
                'l3-routing-vrrp-troubleshooting', 'multicast-troubleshooting']),
        ('工具与 AI 运维', ['app-logging-qos-troubleshooting', 'ovna-deployment-teams-bot']),
       ]),
  dict(id='manuals/awos-ap-guide', book='awos-ap-guide', title='AWOS 5.0.3 · Stellar AP 用户手册',
       subtitle='128 页 · AP 本地管理配置手册（Express 模式 GUI 全参考）',
       route=['集群开局与 PVM 选举', 'SSID 射频调优与内置服务', 'WLAN 安全与高级认证', '运维升级与 Mesh'],
       groups=[
        ('开局', ['cluster-bootstrap-pvm']),
        ('业务', ['ssid-radio-tuning']),
        ('安全', ['wlan-security-enterprise']),
        ('运维', ['ap-ops-upgrade-mesh']),
       ]),
  dict(id='manuals/ov2500-install', book='ov2500-install', title='OV2500 4.9R2 · 安装与升级指南',
       subtitle='326 页 · 网管平台部署手册（三平台/HA/升级链）',
       route=['部署规划与四档规模', '三平台安装流程', 'HA 集群设计与转换', '升级路径与备份恢复'],
       groups=[
        ('规划', ['ov2500-sizing-and-platform-planning']),
        ('安装', ['ov2500-install-on-esxi-hyperv-kvm']),
        ('HA 与升级', ['ov2500-ha-cluster-design-and-conversion', 'ov2500-upgrade-backup-restore']),
       ]),
  dict(id='manuals/ov2500-rap-vpn', book='ov2500-rap-vpn', title='OV2500 4.9R2 · RAP 与 VPN VA 安装',
       subtitle='84 页 · 远程 AP 安全回连方案部署',
       route=['VPN 模式选型与 RAP 注册', 'VPN VA 三平台部署与容量', '数据隧道与 Local Breakout', '四层排障决策树'],
       groups=[
        ('规划', ['rap-vpn-mode-registration']),
        ('部署与配置', ['vpn-va-deploy-capacity', 'rap-data-tunnel-config']),
        ('排障', ['rap-vpn-troubleshooting']),
       ]),
]
'''

s = s.replace("# ============ 课程定义 ============\nCOURSES = [",
              "# ============ 课程定义 ============\n" + NEW + "COURSES = NEW_COURSES  # 旧课程(ov-terra/bootcamp/core)保留 site/ 预构建页面，源 books 未随库分发\n_LEGACY = [")
open("build_site.py", "w", encoding="utf-8").write(s)
print("patched OK")
